### ISSUE TITLE
"Attempted to read or write protected memory" in DirectN.Temp

### ISSUE THREAD

**Issue by ahdung** [smourier/DirectN#44]
Test on windows10 22h2 and windows server 2008 R2 sp1.
https://github.com/smourier/DirectN/blob/cc5b3918e0ca755219372203e7220c287e67931e/DirectN/DirectN.Temp/Program.cs#L56

**Comment by ahdung** [comment]
I solved, in 64bit system, should not specify `Pack=4` here:
https://github.com/smourier/DirectN/blob/cc5b3918e0ca755219372203e7220c287e67931e/DirectN/DirectN/Generated/_D3DLOCKED_RECT.cs#L7

**Comment by smourier** [comment]
Hi,

Yes. The problem is DirectX9 support in DirectN is pretty much hardcoded for x86 (it's not only D3DLOCKED_RECT...)

If you use the source and not the .dll you can change that yourself, but I would like to modify the code to support both x86 and x64. I'll keep the issue open and will try to fix that in a near future...

Thanks :-)

**Comment by smourier** [comment]
This commit [https://github.com/smourier/DirectN/commit/a15d399dc2311ce812038f517d5bca3aba2878ee](https://github.com/smourier/DirectN/commit/a15d399dc2311ce812038f517d5bca3aba2878ee) should improve all that. Note it may change the way to call some DirectX9 interfaces.
