### ISSUE TITLE
CreateDrawingStateBlock first paramater type why is nint ?

### ISSUE THREAD

**Issue by sgf** [smourier/DirectN#48]
![image](https://github.com/smourier/DirectN/assets/2557696/e8b4b441-94da-439d-a77f-1e8e2edaded7)

same with 
![image](https://github.com/smourier/DirectN/assets/2557696/4150cc91-753c-4b55-a8c9-3383b8c05dc5)

**Comment by smourier** [comment]
Because this is how the COM interface method is designed in `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\d2d1.h`:

    STDMETHOD(CreateDrawingStateBlock)(
        _In_opt_ CONST D2D1_DRAWING_STATE_DESCRIPTION *drawingStateDescription,
        _In_opt_ IDWriteRenderingParams *textRenderingParams,
        _COM_Outptr_ ID2D1DrawingStateBlock **drawingStateBlock 
        ) PURE;

This corresponds to this method in MSDN: [ID2D1Factory::CreateDrawingStateBlock(constD2D1_DRAWING_STATE_DESCRIPTION*,IDWriteRenderingParams*,ID2D1DrawingStateBlock**)](https://learn.microsoft.com/en-us/windows/win32/api/d2d1/nf-d2d1-id2d1factory-createdrawingstateblock(constd2d1_drawing_state_description_idwriterenderingparams_id2d1drawingstateblock)) 

The other "methods" with the same name are not COM interface methods, but C++ function, "wrappers" compiled into the calling program, that we cannot call from .NET

    COM_DECLSPEC_NOTHROW
    HRESULT
    CreateDrawingStateBlock(
        CONST D2D1_DRAWING_STATE_DESCRIPTION &drawingStateDescription,
        _COM_Outptr_ ID2D1DrawingStateBlock **drawingStateBlock 
        )  
    {
        return CreateDrawingStateBlock(&drawingStateDescription, NULL, drawingStateBlock);
    }
    
    COM_DECLSPEC_NOTHROW
    HRESULT
    CreateDrawingStateBlock(
        _COM_Outptr_ ID2D1DrawingStateBlock **drawingStateBlock 
        )  
    {
        return CreateDrawingStateBlock(NULL, NULL, drawingStateBlock);
    }

**Comment by smourier** [comment]
The structure is a pointer because the parameter (a struct) is optional.

* If you don't want to pass a `drawingStateDescription`, then just pass `IntPtr.Zero` for the `drawingStateDescription `parameter. 
* If you want to pass a structure, you must allocate a buffer of structure size and marshal the .NET structure to the allocated buffer. But DirectN has a `ComMemory` utility to help you do that easily:

            var desc = new D2D1_DRAWING_STATE_DESCRIPTION();
            desc.antialiasMode = D2D1_ANTIALIAS_MODE.D2D1_ANTIALIAS_MODE_ALIASED;
            // etc...

            ID2D1Factory fac = ...
            using (var mem = new ComMemory(desc))
            {
                fac.CreateDrawingStateBlock(mem.Pointer, etc ...); 
            }

DirectN additionally add extension methods that wraps some methods call so they are easier to use. This is the case for `ID2D1RenderTarget `(but not for *every* COM interface and methods) in `DirectN.ID2D1RenderTargetExtensions`:

![image](https://github.com/smourier/DirectN/assets/5328574/1c2aa7fb-5801-47ec-84ba-6afc253d41ad)

**Comment by sgf** [comment]
I also noticed the second overload before, but since it had too many parameters I neglected to select it.
Thank you for your suggestion.
