### ISSUE TITLE
MFEnumDeviceSources pppSourceActivate should be an array

### ISSUE THREAD

**Issue by andreysaf** [smourier/DirectN#62]
Hello, as I am rewriting a sample for getting a source reader, I noticed that [Functions.MFEnumDeviceSources](https://github.com/smourier/DirectN/blob/c883593d3112f5ff9b6aee15fcf604d71c498cb6/DirectN/DirectN/Generated/Functions.cs#L1129) should be returning an array of devices according to [MS docs](https://learn.microsoft.com/en-us/windows/win32/api/mfidl/nf-mfidl-mfenumdevicesources).

Here is my example usage:
```c#
        public HRESULT CreateCaptureDevice()
        {
            IMFAttributes attributes = null;
            IntPtr[] devices = null;

            HRESULT hr = MFFunctions.MFCreateAttributes(out attributes, 1);
            if (hr.IsError)
            {
                return hr;
            }

            hr = attributes.SetGUID(DirectN.MFConstants.MF_DEVSOURCE_ATTRIBUTE_SOURCE_TYPE, DirectN.MFConstants.MF_DEVSOURCE_ATTRIBUTE_SOURCE_TYPE_VIDCAP_GUID);
            if (hr.IsError)
            {
                return hr;
            }

            hr = Functions.MFEnumDeviceSources(attributes, out devices, out uint count);
            if (hr.IsError)
            {
                return hr;
            }
```
and original from C++:
```c++
HRESULT Media::CreateCaptureDevice()
{
	HRESULT hr = S_OK;
	
	//this is important!!
	hr = CoInitializeEx(NULL, COINIT_APARTMENTTHREADED | COINIT_DISABLE_OLE1DDE);

	UINT32 count = 0;
	IMFAttributes *attributes = NULL;
	IMFActivate **devices = NULL;

	if (FAILED(hr)) { CLEAN_ATTRIBUTES() }
	// Create an attribute store to specify enumeration parameters.
	hr = MFCreateAttributes(&attributes, 1);

	if (FAILED(hr)) { CLEAN_ATTRIBUTES() }

	//The attribute to be requested is devices that can capture video
	hr = attributes->SetGUID(
		MF_DEVSOURCE_ATTRIBUTE_SOURCE_TYPE,
		MF_DEVSOURCE_ATTRIBUTE_SOURCE_TYPE_VIDCAP_GUID
	);
	if (FAILED(hr)) { CLEAN_ATTRIBUTES() }
	//Enummerate the video capture devices
	hr = MFEnumDeviceSources(attributes, &devices, &count);
	
	if (FAILED(hr)) { CLEAN_ATTRIBUTES() }
```

Please let me know if I am using it right. Thank you in advance!

**Comment by smourier** [comment]
Hi,

Most DirectN files automatically generated from Windows SDK header files (in the **Generated** folder) Most of these files are annoted in C/C++ which allows us to build more meaningful arguments but this is not the case of this function. If you look at mfidl.h where it's declared, it looks like this:

```
STDAPI MFEnumDeviceSources(
    _In_                IMFAttributes*                      pAttributes,
    _Outptr_result_buffer_(*pcSourceActivate) IMFActivate***    pppSourceActivate,
    _Out_               UINT32*                             pcSourceActivate
);
```

Which just means `pppSourceActivate `is an output array `IMFActivate*` pointers, but it doesn't say the size of the array. So we cannot marshal that back in non unsafe managed code. We "know" the array length is `pcSourceActivate` because we read the doc, but since it's not annotated we can't generate the information

We could if we were using unsafe raw C# pointers in our declaration but DirectN (and DirectNAot) are designed not to expose raw pointer or unsafe code.

So you have two choices:

1) redefine the function to match documentation. 
2) use the IntPtr you get back in `pppSourceActivate` and convert that to an array of IMFActivate.

The code that's in **Manual** (types) or **Extensions** (utilities) folders was written by hand. So, _MFFunctions_ for example is an add on that partially redefines some methods and makes things easiers for . NET programmers, like everything that's in **Extensions** folder. For example `MFTEnumEx` suffers from the same problem as `MFEnumDeviceSources` so I have redefined it like this for example (this correspond to solution 1):

        [DllImport("mfplat", ExactSpelling = true)]
        public static extern HRESULT MFTEnumEx(
            Guid guidCategory,
            _MFT_ENUM_FLAG Flags,
            IntPtr pInputType,
            IntPtr pOutputType,
            [MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 5)] out IMFActivate[] pppMFTActivate,
            out int pnumMFTActivate);

For solution 2, the code would like that for example (untested):

```
using (var atts = MFFunctions.MFCreateAttributes(1)) // uses utilities
{
    atts.Set(MFConstants.MF_DEVSOURCE_ATTRIBUTE_SOURCE_TYPE, MFConstants.MF_DEVSOURCE_ATTRIBUTE_SOURCE_TYPE_AUDCAP_GUID);
    Functions.MFEnumDeviceSources(atts.Object, out var sources, out var count).ThrowOnError();
    if (count > 0)
    {
        for (var i = 0; i < count; i++)
        {
            // using DirectN ComObject wrapper
            using var activate = new ComObject<IMFActivate>((IMFActivate)Marshal.GetObjectForIUnknown(sources + IntPtr.Size));
            // etc
        }
    }
}
```

**Comment by andreysaf** [comment]
Thanks @smourier!
